### ISSUE TITLE
Load new client data

### ISSUE THREAD

**Issue by amygroshek** [Hyperobjekt/untd-map#13]
- [x] Load and parse new client data files
- [x] Get new client data dict file parsed and merged into active lang file
- [x] Separate out layer toggles for two different layer sets
- [ ] ~~Point features showing up~~ (Addressed in #9 )
- [ ] ~~Tooltips for both point features and polygon features~~ (Addressed in #9 )
- [ ] ~~Get new indicators list rendering in the indicators panel~~ ( Addressed in #10 )
- [ ] ~~Wire up new indicators list to the data in the geojson features~~ ( Addressed in #10 )
